language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
addons:
  ssh_known_hosts: $HOSTNAME
before_deploy:
  - openssl aes-256-cbc -K $encrypted_05d4d4358b2c_key -iv $encrypted_05d4d4358b2c_iv
  -in deploy_rsa.enc -out ~\/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/bot root@$HOSTNAME:/root/bot
  on:
    branch: master
env:
  global:
    secure: Cqcnr5lB1QjRIRFvt0/BpkXTl/wY9ae5FCUwRQVS1hSOKzp1ctS/+3Djh5AILv38VsAYgoVqJFPTyeAeMHdzW6B2ntj+XfahCWEVRF/97v9daPmnYzvrSgmn0QOkwRRbbxvji4L3pEYecr84/a8TfLvbaIyvmaKzxRfhE0t0jPiEzDDQGMrKLFU0G1HRKtbJTIkKqngyilV+M9owmYSPCF0KB/RWuV75vbg11pjRMqzdoALXNIZIT0eSWWlFGeT8iU3ll3Xx2VlUtM4rv/UnvwErBtpyWVLHoCDSRqBd4KCEixLM2eil+9oTA5feP+mt17KaUgWlhg05d5f3nwbb+Y0KI2JJ4l3j/yIOqHMZSMxq+N8cQ7jmBmIUpq+MUK/n4vmx8KjQMwK7V6V4ukQBvTIhqHA62QQjQZRbEZvWmp3YByXwm9iFqiuZUKZHGVse+fuL2vwSlwOqBy4cZElET82BgW2VrEwMjAk4MpQiQSdty4hoq5siGezkExIosaPzJO/lGyo+3PX0PeMe4quF88KgpbdSQ0bzHWGbZnP7L+HGxqpqdP6cBq+cOeIhluIO9VJjSxGwcHGRqCLEnNkcd4PNhWmDn9pD350ZKyvuVQVukKUFMPsShS2aB1QhVVdFX9VP6lhMawiL89jstfvdxUeShWcrO2CUJiTJ3889KnI=
